# Generated by Django 4.1.7 on 2023-04-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_question_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
