# Generated by Django 4.1.7 on 2023-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_alter_box_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='created_by',
            field=models.CharField(max_length=200),
        ),
    ]
