# Generated by Django 4.1.7 on 2023-04-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0008_box_area_box_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='box',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
